version: '3.4'

services:
  kellerbackend:
    image: kellerbackend
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/app.js"]
    networks:
      - back-tier

networks:
  # The presence of these objects is sufficient to define them
  back-tier: {}