# baseURL
@baseURL = http://localhost:3000

###
# User Signup
POST {{ baseURL }}/signup
Content-Type: application/json

{
    "login": "janine",
	"password": "yogi2982",
    "name": "Janine Franken",
    "email": "janine@olconet.com"
}

###
# User Login
POST {{ baseURL }}/login
Content-Type: application/json

{
    "login": "janine",
	"password": "yogi2982"
}

###
# User Logout
POST {{ baseURL }}/logout
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjk5MDI0OTg2LCJleHAiOjE2OTkwMjg1ODZ9.n8VtoCa4SQauuQAqiaSZ_CGVIM8pQEDPc1kdxYdR4fs"

